[build]
# Ensure Nixpacks uses Python
plan = "python"

[phases.setup]
# Install OpenCV dependencies
aptPkgs = ["libgl1", "libglib2.0-0"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn server:app"
